version: "2"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/wastp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_DB: wastpdb
      POSTGRES_PASSWORD: admin
  graphql:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
